#build stage
FROM golang:1.26-alpine AS builder

WORKDIR /app
COPY go.mod go.sum ./

RUN go mod download

copy . .
RUN CGO_ENABLED=0 GOOS=linux go build -o skillpulse .

# Runtime stage
FROM alpine:3.23

RUN apk --no-cache add ca-certificates

WORKDIR /app

COPY --from=builder /app/skillpulse .

EXPOSE 8080

CMD ["./skillpulse"]
